
version: '3.9'

services:
  php:
    build: .
    volumes:
      - ./backend:/var/www/html
    ports:
      - 9000:80
    links:
      - db

  db:
    container_name: 'db_anestesia'
    image: mysql:8.0
    restart: always
    volumes:
     - /var/lib/mysql
    environment:
       MYSQL_DATABASE: anestesia_carioca_db
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: anestesia_carioca
       MYSQL_PASSWORD: anestesia
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9001:80
